# execution-environment.yml
version: 3
dependencies:
  galaxy: requirements.yml

images:
  base_image:
    name: quay.io/ansible/awx-ee:24.6.1 

additional_build_steps:
  append_final: |
    RUN pip install --no-cache-dir openstacksdk