$ANSIBLE_VAULT;1.1;AES256
61316365623531306561376262633264663061356533663733316264373764346138666138336532
3231393864316333376338643731323634623364356235620a333933303065663139393438653636
62646137303766373834313234306134306234353037383466386435376535616561386637626334
6436366338616234350a336566353630633962656333346138646430313235383934363066323530
62356239646235356562363331313538396265616161643339653234373539616363373436663065
66633636356232346432363434643966356663323337343663643062333638643237313664383339
63346333366234353462306633343339613961643866306462356533383264656264623139643066
35643739393138323533
